use rand::seq::SliceRandom;

fn main() {
    let names = vec![
        "Grace",
        "Anthony",
        "Eleanor",
        "Oliver",
        "Lila",
        "Andrew",
        "Emilia",
        "Nathaniel",
        "Ava",
        "William",
        "Hazel",
        "Lucas",
        "Penelope",
        "Benjamin",
        "Isabella",
        "Caleb",
        "Charlotte",
        "Gabriel",
        "Mia",
        "Samuel",
        "Scarlett",
        "Elijah",
        "Sofia",
        "Sophia",
        "Joseph",
        "Amelia",
        "Elizabeth",
        "Alexander",
        "Harper",
        "Henry",
        "Abigail",
        "Emma",
        "Daniel",
        "Chloe",
        "David",
        "Lily",
        "James",
        "Aria",
        "Noah",
        "Madison",
        "Adam",
        "Zoey",
        "Michael",
        "Aurora",
        "Isabelle",
        "Matthew",
        "Avery",
        "Leo",
        "Ella",
        "Lucas",
        "Riley",
        "Ethan",
        "Aubrey",
        "John",
        "Layla",
        "Thomas",
        "Savannah",
        "Daniel",
        "Brooklyn",
        "Joshua",
        "Hannah",
        "Owen",
        "Addison",
        "Christopher",
        "Elizabeth",
        "William",
        "Victoria",
        "Aaron",
        "Grace",
        "Isaac",
        "Gabriella",
        "Jackson",
        "Alyssa",
        "Charles",
        "Natalie",
        "Evan",
        "Taylor",
        "Elijah",
        "Peyton",
        "Jayden",
        "Alexa",
        "Nathan",
        "Ellie",
        "Richard",
        "Piper",
        "Ryan",
        "Kennedy",
        "Nicholas",
        "Sadie",
        "Kyle",
        "Caroline",
        "Jacob",
        "Claire",
        "Adrian",
        "Adalyn",
        "Robert",
        "Faith",
        "Zachary",
        "Lucy",
        "Tyler",
    ];

    let domains = vec![
        "gmail.com",
        "yahoo.com",
        "outlook.com",
        "protonmail.com",
        "aol.com",
        "icloud.com",
        "mail.com",
        "gmx.com",
        "zoho.com",
        "yandex.com",
    ];

    let mut rng = rand::thread_rng();


    //generate 100 random emails
    for _ in 0..10000 {
        let random_name = names.choose(&mut rng).unwrap();
        let random_domain = domains.choose(&mut rng).unwrap();
        //generate a random 2 digit numner to append to the name as a string
        let random_number = rand::random::<u8>();
        let email = format!("{}{}@{}", random_name, random_number, random_domain);
        println!("{}", email);
    }

}
